# Generated by Django 3.0.8 on 2020-08-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', mdeditor.fields.MDTextField()),
                ('dated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('sort', models.CharField(choices=[('bgm', '브금'), ('setting', '옵션'), ('game', '술게임'), ('cheers', '건배사'), ('alcohol', '폭탄주')], default='술게임', max_length=10)),
                ('like', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(related_name='hashtag', to='article.Tag')),
            ],
        ),
    ]
