# Generated by Django 3.0.8 on 2020-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200817_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
