# Generated by Django 3.0.8 on 2020-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_content_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='difficulty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
