# Generated by Django 3.0.8 on 2020-08-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200803_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='member',
        ),
    ]
