# Generated by Django 3.0.8 on 2020-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200828_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], default='d', max_length=1),
        ),
    ]
