# Generated by Django 3.0.8 on 2020-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200801_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
