# Generated by Django 3.0.8 on 2020-08-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
