# Generated by Django 3.0.8 on 2020-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200822_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='article.Tag'),
        ),
    ]
