# Generated by Django 3.0.8 on 2020-08-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200805_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='like',
        ),
        migrations.RemoveField(
            model_name='content',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
