# Generated by Django 3.0.8 on 2020-08-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200801_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
