# Generated by Django 3.0.8 on 2020-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bookmark_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sort',
            field=models.CharField(choices=[('1', '브금'), ('2', '인트로'), ('3', '술게임'), ('4', '건배사'), ('5', '폭탄주')], default='브금', max_length=3),
        ),
    ]
